# Data Cleansing Parkir ITN Malang

## 1. Import & Setup

In [20]:
import io
import re
import numpy as np
import pandas as pd

## 2. Load Dataset

In [21]:
DATA_KOTOR = """ID,Plat_Nomor,Jenis,Merk,Model,Warna,Status,Tanggal,Jam_Masuk,Jam_Keluar,Area
1,N 4521 AB,Motor,Honda,Beat,Merah,Mahasiswa,2026-09-01,07:15,15:30,Kampus 1 - Motor
2,n4521ab,motor,HONDA,beat,merah,mahasiswa,01/09/2026,07:20,15:35,kampus 1 - motor
3,N 1287 CD,Mobil,Toyota,Innova,Silver,Dosen,2026-09-01,08:00,16:00,Kampus 1 - Mobil
4,N 6610 XY,Motor,Yamaha,NMAX,Biru,Mahasiswa,1 Sep 2026,7.45,14.10,Kampus 1 - Motor
5,N 9012 EF,mobil,Honda,Brio,Putih,Dosen,2026-09-02,08:30,08:10,Kampus 1 - Mobil
6,AG 7788 GH,Motor,Suzuki,Satria F150,Biru,Mahasiswa,2026-09-02,09:00,17:00,Kampus 2 - Motor
7,N 3456 IJ,Motor,Honda,Vario 125,Biru,Mahasiswa,2026-09-02,07:50,NULL,Kampus 2 - Motor
8,N-2468-KL,Mobil,Daihatsu,Xenia,Hitam,Staf,2026-09-03,07:30,16:30,kampus 1 - mobil
9,DK 1357 MN,Sepeda Motor,Honda,Supra X 125,Hijau,Tamu,2026-09-03,10:00,11:30,Kampus 2 - Motor
10,N 8642 OP,Motor,Honda,PCX,Oranye,Mahasiswa,2026-09-03,25:10,15:00,Kampus 2 - Motor
11,,Motor,Kawasaki,Ninja 250,Hijau,Mahasiswa,2026-09-04,08:05,12:00,Kampus 1 - Motor
12,N 1111 QR,Mobill,Toyota,Avanza,Abu-abu,Dosn,2026-09-04,08:15,17:45,Kampus 1 - Mobil
13,N 2222 ST,Motor,Honda,Scoopy,Kuning,Mahasiswa ,2026-09-04,07:10,16:20,Kampus 3 - Motor
14,N 3333 UV,Motor,yamaha,Mio,Merah,Mahasiswa,04-09-2026,09:30,13:00,Kampus 1 - Motor
15,B 4444 WX,Mobil,Mitsubishi,Xpander,Coklat,Tamu,2026-09-05,13:00,14:00,Kampus 2 - Mobil
16,N 5555 YZ,Motor,Honda,Vario,Coklat,Mahasiswa,2026-09-05,07:00,07:00,Kampus 1 - Motor
17,N 6666 AA,Motor,Honda,Genio,Maroon,Mahasiswa,2026-09-05,06:45,99:99,Kampus 1 - Motor
18,N 7777 BB,Sepeda,Polygon,Xtrada,Biru,Mahasiswa,2026-09-06,08:00,12:30,Kampus 2 - Motor
19,N 8888 CC,Mobil,Toyota,Fortuner,Putih,Dosen,2026-09-06,08:00,2026-09-07 08:00,Kampus 2 - Mobil
20,N 9999 DD,Motor,Honda,CB150R,Hitam,Staf,2026-09-06,07:30,16:00,Kampus 1 - Motor
21,N 1010 EE,Motor,Yamaha,Aerox,Biru Tua,Mahasiswa,2026-09-07,07:40,15:00,Kampus 2 - Motor
22,N 1010 EE,Motor,Yamaha,Aerox,Biru Tua,Mahasiswa,2026-09-07,07:40,15:00,Kampus 2 - Motor
23,N 1212 FF,Motor,Honda,Beat,Merah,N/A,2026-09-07,08:20,16:10,Kampus 2 - Motor
24,N 1313 GG,Mobil,Suzuki,Ertiga,Silver,Dosen,2027-01-15,09:00,15:00,Kampus 1 - Mobil
25,N 1414 HH,Motor,Honda,Scopy,Krem,Mahasiswa,2026-09-08,7:5,16:00,Kampus 1 - Motor
26,N 1515 II,MOTOR,HONDA,VARIO,BIRU,MAHASISWA,2026-09-08,08:10,17:00,KAMPUS 1 - MOTOR
27,N 1616 JJ,Motor,Honda,,Abu abu,Mahasiswa,2026-09-08,08:30,16:45,Kampus 2 - Motor
28,N1717KK,Mobil,Honda,Jazz,Putih,Staf,2026-09-09,08:00,17:00,Kampus 1 - Mobil
29,N 1818 LL,Motor,Yamaha,Mio,Hijau,Mahasiswa,2026-09-09,07:55,16:05,Kampus 1 - Motor
30,N 1919 MM,Motor,Honda,Beat,Grey,Tamu,9/9/26,12:00,13:15,
"""

df = pd.read_csv(io.StringIO(DATA_KOTOR), dtype=str, keep_default_na=False)
df.head(10)

,ID,Plat_Nomor,Jenis,Merk,Model,Warna,Status,Tanggal,Jam_Masuk,Jam_Keluar,Area
0,1,N 4521 AB,Motor,Honda,Beat,Merah,Mahasiswa,2026-09-01,07:15,15:30,Kampus 1 - Motor
1,2,n4521ab,motor,HONDA,beat,merah,mahasiswa,01/09/2026,07:20,15:35,kampus 1 - motor
2,3,N 1287 CD,Mobil,Toyota,Innova,Silver,Dosen,2026-09-01,08:00,16:00,Kampus 1 - Mobil
3,4,N 6610 XY,Motor,Yamaha,NMAX,Biru,Mahasiswa,1 Sep 2026,7.45,14.10,Kampus 1 - Motor
4,5,N 9012 EF,mobil,Honda,Brio,Putih,Dosen,2026-09-02,08:30,08:10,Kampus 1 - Mobil
5,6,AG 7788 GH,Motor,Suzuki,Satria F150,Biru,Mahasiswa,2026-09-02,09:00,17:00,Kampus 2 - Motor
6,7,N 3456 IJ,Motor,Honda,Vario 125,Biru,Mahasiswa,2026-09-02,07:50,NULL,Kampus 2 - Motor
7,8,N-2468-KL,Mobil,Daihatsu,Xenia,Hitam,Staf,2026-09-03,07:30,16:30,kampus 1 - mobil
8,9,DK 1357 MN,Sepeda Motor,Honda,Supra X 125,Hijau,Tamu,2026-09-03,10:00,11:30,Kampus 2 - Motor
9,10,N 8642 OP,Motor,Honda,PCX,Oranye,Mahasiswa,2026-09-03,25:10,15:00,Kampus 2 - Motor

## 3. Data Understanding

In [22]:
print("Ukuran data:", df.shape)
df.info()

Ukuran data: (30, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          30 non-null     object
 1   Plat_Nomor  30 non-null     object
 2   Jenis       30 non-null     object
 3   Merk        30 non-null     object
 4   Model       30 non-null     object
 5   Warna       30 non-null     object
 6   Status      30 non-null     object
 7   Tanggal     30 non-null     object
 8   Jam_Masuk   30 non-null     object
 9   Jam_Keluar  30 non-null     object
 10  Area        30 non-null     object
dtypes: object(11)
memory usage: 2.7+ KB

In [23]:
for kolom in ["Jenis", "Merk", "Model", "Warna", "Status", "Area"]:
    print(f"\n--- {kolom} ---")
    print(df[kolom].value_counts(dropna=False).to_string())

--- Jenis ---
Jenis
Motor           18
Mobil            6
motor            1
mobil            1
Sepeda Motor     1
Mobill           1
Sepeda           1
MOTOR            1

--- Merk ---
Merk
Honda         14
Yamaha         4
Toyota         3
HONDA          2
Suzuki         2
Daihatsu       1
Kawasaki       1
yamaha         1
Mitsubishi     1
Polygon        1

--- Model ---
Model
Beat           3
Mio            2
Aerox          2
NMAX           1
Innova         1
Satria F150    1
Vario 125      1
Xenia          1
Brio           1
beat           1
PCX            1
Supra X 125    1
Avanza         1
Ninja 250      1
Xpander        1
Vario          1
Genio          1
Scoopy         1
Xtrada         1
Fortuner       1
CB150R         1
Ertiga         1
Scopy          1
VARIO          1
               1
Jazz           1

--- Warna ---
Warna
Biru        4
Merah       3
Putih       3
Hijau       3
Silver      2
Hitam       2
Coklat      2
Biru Tua    2
merah       1
Abu-abu     1
Oranye      1
Kuning      1
Maroon      1
Krem        1
BIRU        1
Abu abu     1
Grey        1

--- Status ---
Status
Mahasiswa     15
Dosen          4
Staf           3
Tamu           3
mahasiswa      1
Dosn           1
Mahasiswa      1
N/A            1
MAHASISWA      1

--- Area ---
Area
Kampus 1 - Motor    9
Kampus 2 - Motor    9
Kampus 1 - Mobil    5
Kampus 2 - Mobil    2
kampus 1 - motor    1
kampus 1 - mobil    1
Kampus 3 - Motor    1
KAMPUS 1 - MOTOR    1
                    1

## 4. Handling Missing Values

In [24]:
df_awal = df.copy()  # simpan salinan untuk perbandingan sebelum/sesudah

for kolom in df.columns:
    df[kolom] = df[kolom].str.strip()

df = df.replace({"": np.nan, "NULL": np.nan, "N/A": np.nan, "-": np.nan})
print(df.isna().sum())

ID            0
Plat_Nomor    1
Jenis         0
Merk          0
Model         1
Warna         0
Status        1
Tanggal       0
Jam_Masuk     0
Jam_Keluar    1
Area          1
dtype: int64

## 5. Plate Number Standardization

In [25]:
def rapikan_plat(x):
    if pd.isna(x):
        return np.nan
    x = re.sub(r"[^A-Za-z0-9]", "", x).upper()        # buang spasi dan tanda hubung
    m = re.match(r"^([A-Z]{1,2})(\d{1,4})([A-Z]{1,3})$", x)
    return f"{m.group(1)} {m.group(2)} {m.group(3)}" if m else np.nan

df["Plat_Nomor"] = df["Plat_Nomor"].apply(rapikan_plat)

## 6. Data Standardization

In [26]:
for kolom in ["Jenis", "Merk", "Model", "Warna", "Status", "Area"]:
    df[kolom] = df[kolom].str.title()

df["Jenis"] = df["Jenis"].replace({"Mobill": "Mobil", "Sepeda Motor": "Motor"})
df["Model"] = df["Model"].replace({
    "Scopy": "Scoopy",        # typo
    "Vario 125": "Vario",     # model sama
    "Nmax": "NMAX", "Pcx": "PCX", "Cb150R": "CB150R",   # title() merusak singkatan
})
df["Warna"] = df["Warna"].replace({"Abu Abu": "Abu-abu", "Abu-Abu": "Abu-abu", "Grey": "Abu-abu"})
df["Status"] = df["Status"].replace({"Dosn": "Dosen"})
df["Status"] = df["Status"].fillna("Tidak Diketahui")

for kolom in ["Jenis", "Merk", "Model", "Warna", "Status", "Area"]:
    print(f"\n--- {kolom} ---")
    print(df[kolom].value_counts(dropna=False).to_string())

--- Jenis ---
Jenis
Motor     21
Mobil      8
Sepeda     1

--- Merk ---
Merk
Honda         16
Yamaha         5
Toyota         3
Suzuki         2
Daihatsu       1
Kawasaki       1
Mitsubishi     1
Polygon        1

--- Model ---
Model
Beat           4
Vario          3
Scoopy         2
Aerox          2
Mio            2
Innova         1
Satria F150    1
Brio           1
NMAX           1
Xenia          1
Ninja 250      1
PCX            1
Avanza         1
Supra X 125    1
Xpander        1
Genio          1
Fortuner       1
Xtrada         1
CB150R         1
Ertiga         1
NaN            1
Jazz           1

--- Warna ---
Warna
Biru        5
Merah       4
Putih       3
Abu-abu     3
Hijau       3
Hitam       2
Silver      2
Biru Tua    2
Coklat      2
Kuning      1
Oranye      1
Maroon      1
Krem        1

--- Status ---
Status
Mahasiswa          18
Dosen               5
Staf                3
Tamu                3
Tidak Diketahui     1

--- Area ---
Area
Kampus 1 - Motor    11
Kampus 2 - Motor     9
Kampus 1 - Mobil     6
Kampus 2 - Mobil     2
Kampus 3 - Motor     1
NaN                  1

## 7. Date Correction

In [27]:
FORMAT_TANGGAL = ["%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y", "%d %b %Y", "%d/%m/%y"]

def parse_tanggal(x):
    if pd.isna(x):
        return pd.NaT
    for fmt in FORMAT_TANGGAL:
        try:
            return pd.to_datetime(x, format=fmt)
        except ValueError:
            continue
    return pd.NaT

df["Tanggal"] = df["Tanggal"].apply(parse_tanggal)
df["Tanggal"].head(12)

0    2026-09-01
1    2026-09-01
2    2026-09-01
3    2026-09-01
4    2026-09-02
5    2026-09-02
6    2026-09-02
7    2026-09-03
8    2026-09-03
9    2026-09-03
10   2026-09-04
11   2026-09-04
Name: Tanggal, dtype: datetime64[ns]

## 8. Time Correction

In [28]:
df["Menginap"] = df["Jam_Keluar"].str.contains(r"\d{4}-\d{2}-\d{2}", na=False)

def rapikan_jam(x):
    if pd.isna(x):
        return np.nan
    m = re.search(r"(\d{1,2})[:.](\d{1,2})$", x)
    if not m:
        return np.nan
    jam, menit = int(m.group(1)), int(m.group(2))
    if jam > 23 or menit > 59:
        return np.nan
    return f"{jam:02d}:{menit:02d}"

df["Jam_Masuk"] = df["Jam_Masuk"].apply(rapikan_jam)
df["Jam_Keluar"] = df["Jam_Keluar"].apply(rapikan_jam)
df[["ID", "Tanggal", "Jam_Masuk", "Jam_Keluar", "Menginap"]].head(12)

    ID    Tanggal Jam_Masuk Jam_Keluar  Menginap
0    1 2026-09-01     07:15      15:30     False
1    2 2026-09-01     07:20      15:35     False
2    3 2026-09-01     08:00      16:00     False
3    4 2026-09-01     07:45      14:10     False
4    5 2026-09-02     08:30      08:10     False
5    6 2026-09-02     09:00      17:00     False
6    7 2026-09-02     07:50        NaN     False
7    8 2026-09-03     07:30      16:30     False
8    9 2026-09-03     10:00      11:30     False
9   10 2026-09-03       NaN      15:00     False
10  11 2026-09-04     08:05      12:00     False
11  12 2026-09-04     08:15      17:45     False

## 9. Handling Duplicates

In [29]:
sebelum = len(df)
df = df.drop_duplicates(subset=["Plat_Nomor", "Tanggal"], keep="first")
print(f"Baris dihapus: {sebelum - len(df)} (dari {sebelum} menjadi {len(df)})")

Baris dihapus: 2 (dari 30 menjadi 28)

## 10. Data Validation

In [30]:
TANGGAL_BATAS = pd.Timestamp("2026-09-30")
AREA_RESMI = ["Kampus 1 - Motor", "Kampus 1 - Mobil", "Kampus 2 - Motor", "Kampus 2 - Mobil"]

masuk = pd.to_datetime(df["Tanggal"].dt.strftime("%Y-%m-%d") + " " + df["Jam_Masuk"], errors="coerce")
keluar = pd.to_datetime(df["Tanggal"].dt.strftime("%Y-%m-%d") + " " + df["Jam_Keluar"], errors="coerce")
keluar = keluar + pd.to_timedelta(df["Menginap"].astype(int), unit="D")   # menginap: keluar hari berikutnya

df["Durasi_Menit"] = (keluar - masuk).dt.total_seconds() / 60

df["Valid_Durasi"] = df["Durasi_Menit"] > 0
df["Valid_Tanggal"] = df["Tanggal"].notna() & (df["Tanggal"] <= TANGGAL_BATAS)
df["Valid_Area"] = df["Area"].isin(AREA_RESMI)

df[["ID", "Plat_Nomor", "Durasi_Menit", "Valid_Durasi", "Valid_Tanggal", "Valid_Area"]]

    ID  Plat_Nomor  Durasi_Menit  Valid_Durasi  Valid_Tanggal  Valid_Area
0    1   N 4521 AB         495.0          True           True        True
2    3   N 1287 CD         480.0          True           True        True
3    4   N 6610 XY         385.0          True           True        True
4    5   N 9012 EF         -20.0         False           True        True
5    6  AG 7788 GH         480.0          True           True        True
6    7   N 3456 IJ           NaN         False           True        True
7    8   N 2468 KL         540.0          True           True        True
8    9  DK 1357 MN          90.0          True           True        True
9   10   N 8642 OP           NaN         False           True        True
10  11         NaN         235.0          True           True        True
11  12   N 1111 QR         570.0          True           True        True
12  13   N 2222 ST         550.0          True           True       False
13  14   N 3333 UV         210.0          True           True        True
14  15   B 4444 WX          60.0          True           True        True
15  16   N 5555 YZ           0.0         False           True        True
16  17   N 6666 AA           NaN         False           True        True
17  18   N 7777 BB         270.0          True           True        True
18  19   N 8888 CC        1440.0          True           True        True
19  20   N 9999 DD         510.0          True           True        True
20  21   N 1010 EE         440.0          True           True        True
22  23   N 1212 FF         470.0          True           True        True
23  24   N 1313 GG         360.0          True          False        True
24  25   N 1414 HH         535.0          True           True        True
25  26   N 1515 II         530.0          True           True        True
26  27   N 1616 JJ         495.0          True           True        True
27  28   N 1717 KK         540.0          True           True        True
28  29   N 1818 LL         490.0          True           True        True
29  30   N 1919 MM          75.0          True           True       False

## 11. Cleaned Dataset

In [31]:
df_flag = df.reset_index(drop=True)
df_bersih = df_flag[df_flag["Valid_Durasi"] & df_flag["Valid_Tanggal"] & df_flag["Valid_Area"]].reset_index(drop=True)

print("Data awal      :", len(df_awal), "baris")
print("Setelah dedup  :", len(df_flag), "baris")
print("Data bersih    :", len(df_bersih), "baris")
print("\nBaris bermasalah:")
df_flag[~(df_flag["Valid_Durasi"] & df_flag["Valid_Tanggal"] & df_flag["Valid_Area"])][
    ["ID", "Plat_Nomor", "Tanggal", "Area", "Durasi_Menit", "Valid_Durasi", "Valid_Tanggal", "Valid_Area"]]

Data awal      : 30 baris
Setelah dedup  : 28 baris
Data bersih    : 20 baris

Baris bermasalah:

,ID,Plat_Nomor,Tanggal,Area,Durasi_Menit,Valid_Durasi,Valid_Tanggal,Valid_Area
3,5,N 9012 EF,2026-09-02,Kampus 1 - Mobil,-20.0,False,True,True
5,7,N 3456 IJ,2026-09-02,Kampus 2 - Motor,NaN,False,True,True
8,10,N 8642 OP,2026-09-03,Kampus 2 - Motor,NaN,False,True,True
11,13,N 2222 ST,2026-09-04,Kampus 3 - Motor,550.0,True,True,False
14,16,N 5555 YZ,2026-09-05,Kampus 1 - Motor,0.0,False,True,True
15,17,N 6666 AA,2026-09-05,Kampus 1 - Motor,NaN,False,True,True
21,24,N 1313 GG,2027-01-15,Kampus 1 - Mobil,360.0,True,False,True
27,30,N 1919 MM,2026-09-09,NaN,75.0,True,True,False

In [32]:
df_bersih

,ID,Plat_Nomor,Jenis,Merk,Model,Warna,Status,Tanggal,Jam_Masuk,Jam_Keluar,Area,Menginap,Durasi_Menit,Valid_Durasi,Valid_Tanggal,Valid_Area
0,1,N 4521 AB,Motor,Honda,Beat,Merah,Mahasiswa,2026-09-01,07:15,15:30,Kampus 1 - Motor,False,495.0,True,True,True
1,3,N 1287 CD,Mobil,Toyota,Innova,Silver,Dosen,2026-09-01,08:00,16:00,Kampus 1 - Mobil,False,480.0,True,True,True
2,4,N 6610 XY,Motor,Yamaha,NMAX,Biru,Mahasiswa,2026-09-01,07:45,14:10,Kampus 1 - Motor,False,385.0,True,True,True
3,6,AG 7788 GH,Motor,Suzuki,Satria F150,Biru,Mahasiswa,2026-09-02,09:00,17:00,Kampus 2 - Motor,False,480.0,True,True,True
4,8,N 2468 KL,Mobil,Daihatsu,Xenia,Hitam,Staf,2026-09-03,07:30,16:30,Kampus 1 - Mobil,False,540.0,True,True,True
5,9,DK 1357 MN,Motor,Honda,Supra X 125,Hijau,Tamu,2026-09-03,10:00,11:30,Kampus 2 - Motor,False,90.0,True,True,True
6,11,NaN,Motor,Kawasaki,Ninja 250,Hijau,Mahasiswa,2026-09-04,08:05,12:00,Kampus 1 - Motor,False,235.0,True,True,True
7,12,N 1111 QR,Mobil,Toyota,Avanza,Abu-abu,Dosen,2026-09-04,08:15,17:45,Kampus 1 - Mobil,False,570.0,True,True,True
8,14,N 3333 UV,Motor,Yamaha,Mio,Merah,Mahasiswa,2026-09-04,09:30,13:00,Kampus 1 - Motor,False,210.0,True,True,True
9,15,B 4444 WX,Mobil,Mitsubishi,Xpander,Coklat,Tamu,2026-09-05,13:00,14:00,Kampus 2 - Mobil,False,60.0,True,True,True
10,18,N 7777 BB,Sepeda,Polygon,Xtrada,Biru,Mahasiswa,2026-09-06,08:00,12:30,Kampus 2 - Motor,False,270.0,True,True,True
11,19,N 8888 CC,Mobil,Toyota,Fortuner,Putih,Dosen,2026-09-06,08:00,08:00,Kampus 2 - Mobil,True,1440.0,True,True,True
12,20,N 9999 DD,Motor,Honda,CB150R,Hitam,Staf,2026-09-06,07:30,16:00,Kampus 1 - Motor,False,510.0,True,True,True
13,21,N 1010 EE,Motor,Yamaha,Aerox,Biru Tua,Mahasiswa,2026-09-07,07:40,15:00,Kampus 2 - Motor,False,440.0,True,True,True
14,23,N 1212 FF,Motor,Honda,Beat,Merah,Tidak Diketahui,2026-09-07,08:20,16:10,Kampus 2 - Motor,False,470.0,True,True,True
15,25,N 1414 HH,Motor,Honda,Scoopy,Krem,Mahasiswa,2026-09-08,07:05,16:00,Kampus 1 - Motor,False,535.0,True,True,True
16,26,N 1515 II,Motor,Honda,Vario,Biru,Mahasiswa,2026-09-08,08:10,17:00,Kampus 1 - Motor,False,530.0,True,True,True
17,27,N 1616 JJ,Motor,Honda,NaN,Abu-abu,Mahasiswa,2026-09-08,08:30,16:45,Kampus 2 - Motor,False,495.0,True,True,True
18,28,N 1717 KK,Mobil,Honda,Jazz,Putih,Staf,2026-09-09,08:00,17:00,Kampus 1 - Mobil,False,540.0,True,True,True
19,29,N 1818 LL,Motor,Yamaha,Mio,Hijau,Mahasiswa,2026-09-09,07:55,16:05,Kampus 1 - Motor,False,490.0,True,True,True

## 12. Save Cleaned Dataset

In [33]:
df_flag.to_csv("data_parkir_flag.csv", index=False)
df_bersih.to_csv("data_parkir_bersih.csv", index=False)

print("File tersimpan: data_parkir_flag.csv dan data_parkir_bersih.csv")
from google.colab import files

files.download("data_parkir_bersih.csv")

File tersimpan: data_parkir_flag.csv dan data_parkir_bersih.csv


# DATA ENRICHMENT

In [34]:

df_bersih["Hari"] = df_bersih["Tanggal"].dt.day_name()

# 2. Mengubah durasi dari menit menjadi jam
df_bersih["Durasi_Jam"] = (
    df_bersih["Durasi_Menit"] / 60
).round(2)

def kategori_durasi(menit):
    if menit <= 120:
        return "Singkat"
    elif menit <= 480:
        return "Sedang"
    else:
        return "Lama"

df_bersih["Kategori_Durasi"] = (
    df_bersih["Durasi_Menit"].apply(kategori_durasi)
)

df_bersih["Kategori_Kendaraan"] = df_bersih["Jenis"].map({
    "Motor": "Roda 2",
    "Mobil": "Roda 4"
})

df_bersih.head(10)

,ID,Plat_Nomor,Jenis,Merk,Model,Warna,Status,Tanggal,Jam_Masuk,Jam_Keluar,Area,Menginap,Durasi_Menit,Valid_Durasi,Valid_Tanggal,Valid_Area,Hari,Durasi_Jam,Kategori_Durasi,Kategori_Kendaraan
0,1,N 4521 AB,Motor,Honda,Beat,Merah,Mahasiswa,2026-09-01,07:15,15:30,Kampus 1 - Motor,False,495.0,True,True,True,Tuesday,8.25,Lama,Roda 2
1,3,N 1287 CD,Mobil,Toyota,Innova,Silver,Dosen,2026-09-01,08:00,16:00,Kampus 1 - Mobil,False,480.0,True,True,True,Tuesday,8.00,Sedang,Roda 4
2,4,N 6610 XY,Motor,Yamaha,NMAX,Biru,Mahasiswa,2026-09-01,07:45,14:10,Kampus 1 - Motor,False,385.0,True,True,True,Tuesday,6.42,Sedang,Roda 2
3,6,AG 7788 GH,Motor,Suzuki,Satria F150,Biru,Mahasiswa,2026-09-02,09:00,17:00,Kampus 2 - Motor,False,480.0,True,True,True,Wednesday,8.00,Sedang,Roda 2
4,8,N 2468 KL,Mobil,Daihatsu,Xenia,Hitam,Staf,2026-09-03,07:30,16:30,Kampus 1 - Mobil,False,540.0,True,True,True,Thursday,9.00,Lama,Roda 4
5,9,DK 1357 MN,Motor,Honda,Supra X 125,Hijau,Tamu,2026-09-03,10:00,11:30,Kampus 2 - Motor,False,90.0,True,True,True,Thursday,1.50,Singkat,Roda 2
6,11,NaN,Motor,Kawasaki,Ninja 250,Hijau,Mahasiswa,2026-09-04,08:05,12:00,Kampus 1 - Motor,False,235.0,True,True,True,Friday,3.92,Sedang,Roda 2
7,12,N 1111 QR,Mobil,Toyota,Avanza,Abu-abu,Dosen,2026-09-04,08:15,17:45,Kampus 1 - Mobil,False,570.0,True,True,True,Friday,9.50,Lama,Roda 4
8,14,N 3333 UV,Motor,Yamaha,Mio,Merah,Mahasiswa,2026-09-04,09:30,13:00,Kampus 1 - Motor,False,210.0,True,True,True,Friday,3.50,Sedang,Roda 2
9,15,B 4444 WX,Mobil,Mitsubishi,Xpander,Coklat,Tamu,2026-09-05,13:00,14:00,Kampus 2 - Mobil,False,60.0,True,True,True,Saturday,1.00,Singkat,Roda 4

In [36]:
df_bersih.to_csv(
    "data_parkir_bersih_enrichment.csv",
    index=False
)

print("File berhasil dibuat!")

File berhasil dibuat!

In [37]:
from google.colab import files

files.download("data_parkir_bersih_enrichment.csv")